### ISSUE TITLE
font-weight seems missing from typography scss

### ISSUE THREAD

**Issue by starchild** [CodyHouse/codyhouse-framework#12]
Not sure if Im missing something, but there seems no global control for font-weights.  This would be great if it could be added.

Thanks.

**Comment by sebastiano-guerriero** [comment]
Hi there 👋! I'm not sure if you're referring to font-weight utility classes (e.g., .text--bold). If so, we don't plan on adding many utility classes, because our framework is mostly the base for the components https://codyhouse.co/ds/components 

If you want to set a font-weight for specific type elements, you can do so in the _typography.scss file, or set your typography rules using the editor https://codyhouse.co/ds/globals/typography

Cheers
