### ISSUE TITLE
Mobile navigation needs trapping

### ISSUE THREAD

**Issue by djmtype** [CodyHouse/codyhouse-framework#35]
When it comes to keyboard access, the mobile menu of the main header should probably include trapping (like the _Dialog_ component). Meaning, when it's toggled open, tabbing through will recycle back to the MENU button instead of tabbing to the main content which lays underneath, and no longer accessible. 

[https://codyhouse.co/ds/components/app/main-header](https://codyhouse.co/ds/components/app/main-header)

**Comment by sebastiano-guerriero** [comment]
Hi there! I'm not 100% sure trapping would be the best approach in this case. You can go back to the navigation by clicking shift+tab (or swift left on a phone). However, it is true blind users don't know they're "leaving" the navigation. Plus the next focusable item could be under the navigation popup, causing issues to users navigating the content with their keyboard. We'll collect more data and get back to this. Thanks for the feedback!

I'm closing this issue because it's not strictly related to the framework, but to a component.
