### ISSUE TITLE
missing xs breakpoint

### ISSUE THREAD

**Issue by starchild** [CodyHouse/codyhouse-framework#7]
Not sure if this is intentional or not, but you're missing the xs breakpoint (in _breakpoint.scss) which also means the following (at least) is also missing (from _grid_layout.scss)

@include breakpoint(xs) {
  @for $i from 1 through $grid-columns {
    .col--xs-#{$i} {
      flex-basis: round-width($i);
      max-width: round-width($i); 
    }
  }
}

**Comment by sebastiano-guerriero** [comment]
Hi there! It's intentional. While developing the components we realized we never used a breakpoint smaller than 600px, so we removed -xs. I do realize now that because we do use the -xs variable in all other cases, someone could take for granted that there's a breakpoint as well and try to use it in their code. We'll give this a second look. Thanks for the heads-up!

**Comment by sebastiano-guerriero** [comment]
Added xs breakpoint
