### ISSUE TITLE
No matching version found for codyhouse-framework@^2.9.1

### ISSUE THREAD

**Issue by retroriff** [CodyHouse/codyhouse-framework#97]
Hello,

before trying CH3 I updated to 2.9.1 but I am getting this message:

> No matching version found for codyhouse-framework@^2.9.1

```js
 "codyhouse-framework": "^2.9.1"
```

**Comment by claudia-romano** [comment]
Hi there, sorry for the issue! Should be fixed now. Cheers!

**Comment by retroriff** [comment]
@claudia-romano Now it works, thanks!

I am still havind many warnings with 2.9.1 Should I update my node-sass or sass-loader?

> : Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
> Recommendation: math.div(100% * $i * 100, $grid-columns)
> More info and automated migrator: https://sass-lang.com/d/slash-div

**Comment by claudia-romano** [comment]
CodyFrame 2.9 does not support the new SASS module system; so if you are using dart sass (rather than node-sass), you will get these warnings also after upgrading to CodyFrame 2.9.1. 
Is using node-sass an option for you? That would fix your issue.

Fyi, we just released CodyFrame 3.0:
https://codyhouse.co/blog/post/codyframe-3-0

There are breaking changes so we do not suggest to upgrade from 2.9 to 3.0. But for new projects, you will be able to use dart-sass with CodyFrame 3.0. 

Cheers!
